name: test
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-pkg-mod-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-pkg-mod-

      - name: Run Linter
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.31
          args: --tests --disable-all --enable=goimports --enable=golint --enable=govet --enable=errcheck --enable=staticcheck --skip-dirs=internal/ipaneologd/statik --timeout=10m0s

      - name: Run Test
        run: go test -v ./...
